### ISSUE TITLE
Crash when running on device without libOpenCL.so

### ISSUE THREAD

**Issue by arifhn** [ARM-software/armnn#129]
Android app crash while loading native library linked with Arm NN if the device don't have libOpenCL.so.
Arm NN and Arm CL compiled with OpenCL support.

I've tried Arm CL before, and the behaviour is different. Arm CL don't crash, even if loaded on device without OpenCL support.

Can we get the same behaviour with Arm NN?

**Comment by MatthewARM** [comment]
Hi @arifhn when built with the OpenCL backend ArmNN directly depends on libOpenCL.so because of some code in armnn/src/backends/cl/ClContextControl.cpp. 

This code releases and reacquires the OpenCL runtime every now and again so that OpenCL implementations using LLVM are able to completely free their working memory. We have found that long-running sessions of ArmNN using our android-nn-driver need this to avoid memory accumulations in the OpenCL system.

If you are just loading a single network in your application, you don't need any of that and you could remove all of the OpenCL code within ClContextControl.cpp. You'd then be able to remove the link to OpenCL from CMakeLists.txt (`target_link_libraries(armnn ${OPENCL_LIBRARIES})`).

Alternatively a proper fix could be to indirectly call the OpenCL routines from ClContextControl, using 'dlopen/dlsym' to find them. I don't know if this would be possible for those calls.

Please let me know your thoughts. It might be the kind of discussion best had on the developer mailing list https://lists.linaro.org/mailman/listinfo/armnn-dev rather than on an issue tracker.

All the best,
Matthew

**Comment by arifhn** [comment]
Hi @MatthewARM, thanks for your answer.

FYI, I'm Android developer with a little C/C++ knowledge. So I didn't know in details about what you explained above, but I think I can guess it in general. So this design is needed to avoid memory accumulations (or leak?). CMIIW

In my opinion, for Android application it is better if we can cover many devices with minimal APK variant. So, its mean the native library also need to support it.

I have question about your answer in 3rd paragraph
> If you are just loading a single network in your application, ...

Let's say I just want to run only mobilenet in my application, and the classification could be run repeatedly. Does it mean that I can modify ClContextControl to remove all OpenCL direct dependencies?

Another alternative, could we compile Arm NN with shared Arm CL? My idea is to create two Arm NN libs, one with Open CL and the other without Open CL. Then I think we can handle the System.loadLibrary with try-catch. Currently we can do this, but the problem is libarmnn.so size. It is about 75 MB.

**Comment by MatthewARM** [comment]
Wow, libarmnn.so should be around 10-11MB when compiled with both the OpenCL and NEON backends. I'll double-check that, but perhaps you have not stripped debugging symbols from your build?

The fact that ArmNN links directly to libOpenCL.so is an unfortunate side-effect of the workaround we are doing to avoid memory "accumulations" (like a leak, but you can work around it :-) ) in the OpenCL driver. If you are only running one instance of mobilenet, then you can modify ClContextControl to remove all direct OpenCL dependencies.

Your last suggestion, of using a shared Arm CL would also work, but should be unnecessary if you can remove direct linking to libOpenCL from ArmNN.

Good luck,
Matthew

**Comment by arifhn** [comment]
Hello,

Sorry for late reply. I've successfully modified ClContextControl to remove all OpenCL deps.

And for the libarmnn.so size, you are correct. After stripped the size reduced to 14MB.

Thank you for your ssupport.
