### ISSUE TITLE
Issue with TfLiteMobileNetSsd-Armnn

### ISSUE THREAD

**Issue by liviolima80** [ARM-software/armnn#147]
Dear all, 
I tried to run the TfLiteMobileNetSsd-Armnn example with release 19_02 but I have the following error

WARNING: Layer of type Activation is not supported on requested backend CpuAcc for data type Unsigned8 (reason: Neon: Logistic Activations unsupported with QAsymm8 data type.), falling back to the next backend.
ERROR: Layer of type Activation is not supported on any preferred backend [CpuAcc ]
InferenceModel error : Optimize returned nullptr

Is this example fixed in release 19_02?

Regards

**Comment by MatthewARM** [comment]
That's odd, are you sure that you're using the 19.02 Compute Library?

**Comment by MatthewARM** [comment]
Ah got it, Logistic is on CpuRef and GpuAcc, not on CpuAcc yet:

Logistic support for TensorFlow Lite parser.
Logistic support for GpuAcc backend.

So if you add CpuRef to the end of your list of compute devices, it should work fine. You'll need to do that anyway because the SSD Detection Postprocess layer is provided by CpuRef.

**Comment by liviolima80** [comment]
Thanks @MatthewARM ,
using both CpuAcc and CpuRef as compute device solve the issue
