### ISSUE TITLE
Can I change  between cpuAcc and gpuAcc dynamically?

### ISSUE THREAD

**Issue by mcdman007** [ARM-software/armnn#149]
Dear all.

In optimize(), set cpuAcc and gpuAcc as values for backendPreferences, and then infer through EnqueueWorkload().
However, it seems that the "compute device" is determined by the order given by backendPreferences.
Is there a way to select "compute device" when inferring?
I want to use cpuAcc when the current gpu is busy, otherwise use gpuAcc when the current cpu is busy.

Regards.

**Comment by MatthewARM** [comment]
Hi @mcdman007 that's a good suggestion, I'm afraid it's a little hard to achieve right now.

At the moment all backend selection is done 'statically', ie. one backend selected for each workload in the optimiser. We'd like to make that more intelligent - ie. instead of using the order provided by the user, select GPU and CPU depending on which will make the net run faster. However, this would still be static.

For your case, you need a feature that we're calling 'dynamic heterogeneous scheduling'. You can use a workaround now, which is to optimize the net twice - once for GPU, and once for CPU. Then you dynamically choose which loaded network to run.  In order for this to work, you'll need enough RAM to have the model loaded twice.

Hope this helps,
Matthew

**Comment by mcdman007** [comment]
Hi, @MatthewARM
Thank you for your reply.
I tested for your workaround.
As you mentioned, my program used more memory.

Regards.
