### ISSUE TITLE
cross build error 

### ISSUE THREAD

**Issue by pure-water** [ARM-software/armnn#156]
Hi 
  I encountered some errors when cross build arm nn from X86 to ARM64 machine.  

   a. When I followed the instruction in the  using protobuf 3.5.1. I always havePROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:4:0:
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc. 

  I tried and there is no conflict of protoc version as discussed in the website. 

  b. When I changed to protoc-3.7.0. Then I can build every step OK unti the last step to build armnn

libarmnnCaffeParser.so: undefined reference to `google::protobuf:*
 
 Any help on how to solve this? 

Regards
Yao

**Comment by MatthewARM** [comment]
Hi @pure-water,

a. This will happen if the version of protoc used in the build of caffe is different from the version of protobuf declared in the headers being used while building. 

b. This will happen if the build system cannot successfully link to libprotobuf.so

In both case the most common reason while cross-compiling is that the build system is incorrectly using HOST headers/libraries instead of using TARGET headers/libraries.
If you set the VERBOSE environment variable to 1 while building, you will see the full compiler and/or linker command of the step that failed. Then we can figure out why it is failing. Ie. where you build armnn with `make`, instead use:
`VERBOSE=1 make`

Hope that helps,
Matthew

**Comment by MatthewARM** [comment]
Hi @pure-water hopefully you managed to fix the problem, but if not please re-open this ticket.
