### ISSUE TITLE
Support for Mobilenet in Tf

### ISSUE THREAD

**Issue by liviolima80** [ARM-software/armnn#189]
Dear all,
I'd like to know if ARM planned to support the use of Mobilet with Tf parser. 

Running Mobilenet SSD Detector generates the following error:

InferenceModel error : Cycle detected in graph  at function LoadGraphDef

Thanks

**Comment by MatthewARM** [comment]
Hi @liviolima80 is that with the 19.02 release or with master? It shouldn't produce that error message (it should probably produce an error message about unsupported operators or something).

For mobilenet we're concentrating on supporting it via the Tensorflow Lite parser, as the Tensorflow -> Tensorflow Lite tooling for Mobilenet is very good and does a lot of the cleaning / sanitising / optimising that we would otherwise have to perform in the Tensorflow parser.

Hope that helps,
Matthew

**Comment by liviolima80** [comment]
Hi @MatthewARM ,
the error is with the 19.02 release

The problem is that in my personal experience the quality of the detection for Tensorflow model is higher than the corrisponding Lite model converted with Tensorflow tools

Livio

**Comment by MatthewARM** [comment]
Really? That's very interesting, I wonder why. This is for a FP32 model in both cases? (ie. you're not quantizing when exporting to TfLite, are you?)

Please can you try the Tensorflow model with the master branch? I'm wondering if you are hitting a bug that we recently fixed.

**Comment by psyhtest** [comment]
> The problem is that in my personal experience the quality of the detection for Tensorflow model is higher than the corrisponding Lite model converted with Tensorflow tools

I can corroborate that from our [MLPerf experience](https://github.com/mlperf/inference/tree/master/edge/object_detection/ssd_mobilenet/tflite#reference-accuracy): mAP 23.11% for TF vs. 22.35% for TFLite. We are looking for an explanation, but even Google colleagues are surprised.

**Comment by liviolima80** [comment]
Hi @MatthewARM ,
Tensorflow model is FP32, and I tried 3 possible configurations for Tf -> Lite conversion:
- FP32 data without output post-process. I did output post-process by myself implementing non-max suppression
- FP32 data with post-process
- UINT8 data with post-process

But I had similar behaviour. I did not measure any mAP score, but actually I use the detector on unknow images and evaluate the quality of the bounding box generated. In many cases the bounding boxes between TF and Lite are identical, in other images are similar but still good and in other the bounding boxes of TfLite have poor accuracy compared to Tf.

I will try to test the master branch in order to check if the error is fixed

**Comment by liviolima80** [comment]
Hi guys,
to have an example of the difference between TF and TFLite I tried diffrent detector models on an interesting test image. 

I downloaded from tensorflow model zoo the following checkpoint data: 
- ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03
- ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18

Then I performed Tf -> TfLite conversion and I tested 5 configurations : 
- TF floating point data
- TF quantized data
- TFLite floating point data with embedded output post-processing
- TFLite floating point data without embedded output post-processing and my own implementation of non-max suppression
- TFLite quantized data with embedded output post-processing

For all the configurations I filtered the boxes with score lower than 0.5

As you can see from attached images the differences between TF and TFLite seem higher for float data (the score for dog goes under 0.5 in TfLite while is 0.6 in Tf), while for quantized data the boxes are very similar (but not identical) 

Obviously since the float and quantized models comes from diffrent training it is hard to compare them

[detector_comparison.zip](https://github.com/ARM-software/armnn/files/3183298/detector_comparison.zip)

**Comment by psyhtest** [comment]
Hi @liviolima80! To make images easier to compare, I've arranged them in a table.

For the floating-point models, we go from poorly localized bicycle and well-localized dog with TF, to slightly better localized bicycle and poorly localized dog with TFLite and embedded postprocessing, to no dog with TFLite and custom posprocessing.

For the quantized models, both TF and TFLite give similar results (well-localized dog; well-localized bicycle; spurious second bicycle detected) 

| Framework | Option | Result | Comment |
|-|-|-|-|
| TF | float | ![tf_float](https://user-images.githubusercontent.com/6597818/57909995-14197000-787c-11e9-922d-cb1a1ccbd4ca.jpg) | Poorly localized bicycle |
| TFLite | float, embedded postprocessing | ![tflite_float_nopost](https://user-images.githubusercontent.com/6597818/57909992-14197000-787c-11e9-9922-aefb430f0651.jpg) | Slightly better localized bicycle; poorly localized dog |
| TFLite | float, custom postprocessing | ![tflite_float_post](https://user-images.githubusercontent.com/6597818/57909994-14197000-787c-11e9-9259-531617359506.jpg) | Slightly better localized bicycle; no dog |
| TF | quantized | ![tf_quantized](https://user-images.githubusercontent.com/6597818/57909996-14197000-787c-11e9-99e5-c0eb72cedde0.jpg) | Well-localized bicycle; spurios second bicycle detected |
| TFLite | quantized | ![tflite_quantized](https://user-images.githubusercontent.com/6597818/57909993-14197000-787c-11e9-8bb6-ae4f24031fec.jpg) | Well-localized bicycle; spurios second bicycle detected; **similar to TF quantized** |

**Comment by MatthewARM** [comment]
Oooh. Have you shown this result to the Tensorflow folks, @psyhtest ?

**Comment by psyhtest** [comment]
@MatthewARM I've generally made them aware of significant differences via [MLPerf](https://github.com/mlperf/inference/blob/master/edge/object_detection/ssd_mobilenet/tflite/README.md#ssd-mobilenet-non-quantized). They acknowledged that the mAP difference of 0.75% was higher than expected, but did not make any suggestions as to how to minimize it :man_shrugging:

I've also made them aware of a [bug](https://github.com/ctuning/ck-mlperf/blob/master/package/model-tflite-mlperf-ssd-mobilenet/README.md#step-1-modelckpt-to-tflite_graphpb) which is still not fixed upstream. This bug stubbornly embeds 'fast_nms` even if `regular_nms` is requested, which is why we may see poor dog and bicycle localization with `fast_nms` in @liviolima80's example.

By the way, @liviolima80, is this image from COCO 2014 or 2017? If so, what's its id? I would like to construct a reproducible test case via [CK](http://cknowledge.org). We are trying to aggregate all similar observations and possible solutions, so the community can build upon collective experience instead of wasting time and effort!

**Comment by liviolima80** [comment]
@psyhtest Thank you for the further analisys you did on my observations.

I took the image from Darknet repository (dog.jpg)

https://github.com/pjreddie/darknet/tree/master/data

**Comment by james-conroy-arm** [comment]
Hi @liviolima80 ,

Are you still experiencing issues with the TensorFlow MobileNet SSD model?

Cheers,
James
