### ISSUE TITLE
Cortex-R and Tensorflow

### ISSUE THREAD

**Issue by edhyah** [ARM-software/armnn#19]
Hi there,

I was wondering if ARM NN will support Cortex-R processors. Also, around when will ARM NN support Tensorflow?

Thanks,
Edward

**Comment by MatthewARM** [comment]
Hi @edhyah,

Sorry for the long delay before replying to you.

If your Cortex-R has NEON and enough memory, we don't know any reason why it wouldn't work. However, we don't test on any Cortex-R platforms internally. We would be interested in hearing more about your use-case, so if you have an Arm support contract you could follow this up with your support channel.

There is some Tensorflow support in the latest ArmNN release. You can see what is supported in the documentation at armnn/src/armnnTfParser/TensorFlowSupport.md. If your model doesn't work with the current ArmNN release, please let us know what is missing so that we can fit it into our prioritisation.

Hope this helps,

Matthew

**Comment by edhyah** [comment]
Hi @MatthewARM,

We are looking to deploy a safety-critical test platform for mobile robot purposes, and Cortex-R processors are "optimized for hard real-time and safety-critical applications." Hence, we've bought the [TMS570LC4357](http://www.ti.com/product/TMS570LC4357) processor, but also want to use ArmNN to fuel our learning.

Is NEON a requirement for a processor to use ArmNN? It seems like only Cortex-R52's support NEON.

Thanks,
Edward

**Comment by MatthewARM** [comment]
Hi @edhyah,

Currently ArmNN has support for NEON CPU acceleration and OpenCL GPU acceleration only. The Cortex-R5F that you are using will therefore not be supported.

I'm afraid I can't really help any more other than to suggest that if you contact support through https://www.arm.com/support/contact-support they will be able to put you in touch with someone who knows about Arm hardware and software products targeting the robotics industry,

**Comment by MatthewARM** [comment]
Hi @edhyah I've asked around a bit and apparently the CMSIS library has a Cortex-R variant supported by TI in Code Composer Studio.

CMSIS contains optimised routines for matrix multiplication which you can use to directly implement neural network layers.

We intend to have a CMSIS export path for ArmNN in a future release (as described at https://developer.arm.com/products/processors/machine-learning/arm-nn) but I'm afraid that I cannot commit publicly to a timeline for that.

**Comment by MatthewARM** [comment]
Hi @edhyah I hope this answers your questions for the moment. Please get in touch with anything else.
