### ISSUE TITLE
Different speedup and processor utilization with different networks

### ISSUE THREAD

**Issue by FSet89** [ARM-software/armnn#218]
I tested armnn with two neural networks and I noticed that the speedup is very different in the two cases. The setup is the following:
**SoC**: RK3399 (2 A72 + 4 A53)
**Reference inference setup**: Python + Caffe + OpenBlas using 2 threads (i.e. the 2 A72 cores)
**Test setup**: armnn + NEON + Compute Library, no quantization, .caffemodel files. Using the ExecuteNetwork script.
**Neural networks**:
- Standard [Googlenet](https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet) (28MB)
- Custom network, based on Googlenet but with only two inception blocks and less feature maps in the most computational-heavy convolutions (1.1MB)

The inference time for Googlenet goes from 3.7 s (reference setup) to 2.57 s (armnn). The inference time for the custom network is basically the same (0.077 s) in both cases. Moreover, the measured inference time is much closer to the theoretical one with googlenet (2.57 vs 2.22) with respect to the custom network (0.07 vs 0.02).
I would like to understand where do this differences come from. Is it a matter of network design? If so, what should I take into consideration in order to maximize the processor utilization?

**Comment by MatthewARM** [comment]
Hi @FSet89 it mostly depends on the shape of the convolutions (ie. input, output dimensions, and filter shape). I would suggest that you make use of Arm NN profiling dumps to get per-layer information, then you will be able to see the effects of changing the number of feature maps between googlenet and the custom model.

Another issue will be that fixed overheads on the model input and output will have more of a relative effect on smaller models. You'll be able to see that on the profiling output also.

Yet another interesting experiment would be to run on the 4 A53s rather than the 2 A72s, to see whether a larger number of weaker cores could be useful. I believe the Compute Library has a particularly well optimised multi-threaded kernel that can be used when the number of cores is a multiple of 4.

Hope that helps,
Matthew

**Comment by FSet89** [comment]
Hi @MatthewARM , thank you for your support. I have a few questions:
- can you indicate me some reference to understand how the shape of the convolutions affect the performance in armnn?
- how can I exploit the profiler functionalities, other than simply checking the inference time in each layer?
- how can I use the multi-threaded kernel in Compute Library with armnn? Is there some documentation about?

**Comment by MatthewARM** [comment]
Hi @FSet89,

* can you indicate me some reference to understand how the shape of the convolutions affect the performance in armnn?
That would be hard to summarise. Compute Library contains many different versions of convolution, which are known to be efficient in certain circumstances for certain hardware. I can get someone from that team to comment here.
* how can I exploit the profiler functionalities, other than simply checking the inference time in each layer?
When using ExecuteNetwork pass the "-e" option (enable event-based profiling)
* how can I use the multi-threaded kernel in Compute Library with armnn? Is there some documentation about?
The multithreaded kernels are enabled by default, and Compute Library selects which one is best, based on your processor architecture and number of threads.

**Comment by GeorgeARM** [comment]
Hello @FSet89 ,

As @MatthewARM mentioned trying to get a per-layer breakdown might be useful.
Some of the reasons that you see a difference could be:
- Less 3x3 convolutions in your custom model than the original. 3x3 fp32 convolutions usually get optimized using Winograd which can boost significantly your model.
- Different GEMM shapes due to different layer configurations.

We have a [googlenet](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_googlenet.cpp) model example at Compute Library level which might help you understand the differences at lower kernel level.
You can clone Compute Library from here:
```
git clone https://review.mlplatform.org/ml/ComputeLibrary
```
Build using:
```
scons arch=arm64-v8a os=linux gles_compute=0 opencl=0 neon=1 timers=1 debug=0 Werror=1 asserts=0 examples=1 benchmark_examples=1 -j8
```
And then run the model to get a breakdown of all the kernels:
```
taskset <cpu_mask> ./benchmark_graph_googlenet --iterations=10 --instruments="wall_clock_timer_ms,scheduler_timer_ms"
```
_Note: These benchmarks are experimental at the moment_

**Comment by gmiodice** [comment]
Hi @FSet89 ,

another interesting aspect to consider might be related to the fully connected (FC) layer if present in your custom network. I don't know the architecture for your custom GoogleNet but it would be good to evaluate what are the dimensions for the input tensor of Fully Connected layer. 
If the dimensions in the custom network are greater than dimensions in GoogleNet, you might be limited more than before by the memory transfers of FC layer because memory bound. From what I understand the custom network has fewer inception blocks so, if this is the case or the FC layer is exactly the same as before, the exec. time spent on this last layer might be not not negligible and than not able to achieve high processor utilization.

Of course without knowing the architecture is difficult to understand what is limiting the processor utilization but I hope this can help anyway.

Thanks,
Gian Marco

**Comment by FSet89** [comment]
Hi all,
thank you for your support and clarifications. 
Taskset revealed that armnn provides an improvement on the inference time when the 4 A53 cores are employed (from 181 ms to 153 ms, ~18% boost).
As Gian Marco suggested, our DNN appears to be memory bound, with more than 10 Gbit/s for the total network inference. In particular, the input to the last FC layer is a 36x23 image with 120 channels, i.e. more data than Googlenet. We will try to change the pooling in our network and to perform a memory analysis for each layer. 
Gian Marco: as per slide 31 of your presentation. Given that our network is memory bound, can you specify how to answer the question "Can we use a different algorithm, i.e. FFT?". Is it possible using armnn?

**Comment by gmiodice** [comment]
Hi @FSet89 ,

great to know you were able to improve the performance by 18%! Regarding the question "can we use a different algorithm?" the answer is "no, we can't at armNN level because armNN relies on the heuristic selection implemented in the Compute Library. The Compute Library should be able to pick up the optimal algorithm for each convolution layer configuration. For instance, if you have a big kernel size (i.e. 9x9 with few OFMs), the Compute Library should use FFT or Direct Convolution

Hope this can help.
Thanks

**Comment by Colm-in-Arm** [comment]
Hi @FSet89,

I think we've answered most of your questions here. Feel free to open a new issue if there's more to discuss.

Colm.
