### ISSUE TITLE
Arm build error

### ISSUE THREAD

**Issue by yeshwanthramakrishna98** [ARM-software/armnn#22]
Hi,
I am trying to build arm environment on RPi and im following the installation procedure present in the official  website.
While building, after the cmake command i encountered some errors regarding ARMCOMPUTE path i manually set them to Compute library folder in the CMakeCache.txt file which is present in armnn folder.
![screenshot from 2018-06-14 12-13-10](https://user-images.githubusercontent.com/28252978/41652702-7d2ee104-74a1-11e8-8f32-ba813660ec90.png)

And after executing the command it showed warnings that " targets may link only to libraries. CMake is dropping the item" for some items.

I ignored that and proceeded with 'make' it is showing file not found for the headers mentioned, for some files i set manually the whole path but it is asking for all the files mentioned in header.

![screenshot from 2018-06-19 11-37-47](https://user-images.githubusercontent.com/28252978/41652740-9c1c17c6-74a1-11e8-946e-8402b413b763.png)

is it because of the warning it was showing or is there any way to resolve this issue?

Thank you,

Yeshwanth R

**Comment by MatthewARM** [comment]
Hi @yeshwanthramakrishna98,

I am assuming that you are following the instructions at:
https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow/building-the-environment and you have succesfully built the Compute Library in step 1.

I think the problem is where you are setting `ARMCOMPUTE_ROOT=/home/pi/ComputeLibrary/src`. The instructions should say "the path of your Compute Library directory", ie. for you `/home/pi/ComputeLibrary`.

Similarly, you should set `ARMCOMPUTE_BUILD_DIR=/home/pi/ComputeLibrary/build` if you are using the default location as described in the instructions.

You should not need to specify ARMCOMPUTE_INCLUDE as it will be generated from ARMCOMPUTE_ROOT.

I hope this fixes your build problem,

Matthew
