### ISSUE TITLE
FullyConnected input dimensions

### ISSUE THREAD

**Issue by Rob-Hughes-Arm** [ARM-software/armnn#241]
The validation code for Fully Connected layers in WorkloadData.cpp requires that the input tensor to fully connected is either 2D or 4D. 2D tensors are presumably interpreted as (input channels, output channels) and 4D tensors presumably have an "implicit reshape" where the 3 input dimensions are collapsed to one.

All the parsers however insert an *explicit* reshape to turn the input of FC into 2D.

Therefore it seems that the 4D support superfluous and arguably confuses the API. I would like to suggest that 4D input are deprecated and eventually removed. This would make the authoring of a backend simpler as the backend needs to deal only with 2D inputs.

**Comment by MatthewARM** [comment]
The 2D input should be (num batches, num inputs), and the 2D weights are (num outputs, num inputs).

Because several of our supported frameworks support 4D input (which gets implicitly reshaped as you surmise) I think we had some discussion in the past about what ArmNN should accept.

The current thinking is that ArmNN should accept 2D inputs, weights, and outputs and 1D bias only. Any "implicit reshaping" needed for compatibility with the frameworks should be inserted explicitly by the parser for that framework.  Any remaining references to 4D inputs in core ArmNN should be dead code and can be removed. Any 'fused reshape' that a particular backend can do should be performed as a target-specific optimisation by that backend.

I'd be happy to get your opinion on this. Also very happy if you can contribute improvements to the code :-)

**Comment by MatthewARM** [comment]
As discussed, it should be safe to remove the references to 4D input in WorkloadData.cpp and elsewhere if still present.

**Comment by Colm-in-Arm** [comment]
WIP review for this change. Some outstanding work in the Caffe parser.

**Comment by Colm-in-Arm** [comment]
So it turns out that both Caffe and Tendorflow parsers do allow 4D fully connected type layers. As this is functionality that is currently working and being actively tested via the Mnist network we won't remove it. 

If a backend does not want to support 4D inputs for fully connected then it can fail the appropriate IsSupported call. The user can then decide to fall back to another backend.

This is the review that will be abandoned: 
https://review.mlplatform.org/c/ml/armnn/+/3007
