### ISSUE TITLE
Is there a functional interface one can use?

### ISSUE THREAD

**Issue by RuABraun** [ARM-software/armnn#290]
I want to use ArmNN to speed up inference on android. Currently my float matmuls are taken care of by openBlas, I'm expecting ArmNN to be faster on android.

From what was shown in the "SimpleSample", I would have to throw away the existing code which saves the graph structure from the toolkit I'm using (kaldi), and replace it with ArmNN's graph thing. However, I don't want to have to effectively change the toolkit I'm using, and would rather just swap out the existing GEMM calls from openBlas to some efficient implementation of yours instead.

Does such an interface exist? One where I would pass in existing arrays of weights, biases, inputs & outputs, and the function would just do the MM?

If not, how bad of an idea would it be if I had each of my float FC layers be a network by themselves?

**Comment by MatteoArm** [comment]
Hi @RuABraun,

Following up to your question on LinkedIn as well, the short answer is no, there is no functional API in ArmNN.

Due to the heterogeneous design goals of Arm NN, we wouldn't be able to offer the same functionality through both the existing graph API and a different function-call based API.
If the user wishes more low-level functional control, then they can target ComputeLibrary directly, but then you'll have to handle the scheduling of the workloads yourself.

I hope this helps
Matteo

**Comment by RuABraun** [comment]
Okay thank you! I'll look into the ComputeLibrary.
