### ISSUE TITLE
Allow to use shared version of Arm Compute Library

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#326]
Adding the following lines to `cmake/GlobalConfig.cmake` is ok to use shared version of Arm Compute Library:
```
find_library(ARMCOMPUTE_LIBRARY_DEBUG NAMES arm_compute)
find_library(ARMCOMPUTE_LIBRARY_RELEASE NAMES arm_compute)
find_library(ARMCOMPUTE_CORE_LIBRARY_DEBUG NAMES arm_compute_core)
find_library(ARMCOMPUTE_CORE_LIBRARY_RELEASE NAMES arm_compute_core)
```

But I am not sure it does not break `find_library` for static version of Arm Compute Library.

**Comment by MatthewARM** [comment]
Rather than changing GlobalConfig.cmake, can this be done by setting -DARMCOMPUTE_LIBRARY_X and -DARMCOMPUTE_CORE_LIBRARY on the cmake command line when doing the package build?

**Comment by ggardet** [comment]
> Rather than changing GlobalConfig.cmake, can this be done by setting -DARMCOMPUTE_LIBRARY_X and -DARMCOMPUTE_CORE_LIBRARY on the cmake command line when doing the package build?

I do not know, but it does not look very clean to proceed like this.

**Comment by MatthewARM** [comment]
No? Aren't there two problems here:
1. The compute library by default has different library names for its static and shared library files.
2. Arm NN defaults to linking to the static library.

Your proposal of adding linking to the shared library (I presume, after the lines which currently link to the static library) will make it try static first, and then if that fails then try shared. Is that a reasonable behavior for a developer to expect?

I presume your goal is that in a package-managed system, the armnn package will depend on the compute library package. In this setup, is it more normal to force the build system to do what is required (ie. set the library to link to explictly) or is it more normal to increase the sophistication of the build system so that it handles this case 'automatically'?

I'd appreciate hearing your thoughts.

**Comment by ggardet** [comment]
1. Compute library should probably have the same name for its static and dynamic libs, just the extension should differ (`.a` vs `.so`).
2. Probably better to use dynamic linking first, and fallback to static linking as it is what most (all?) distros will use. But it does not matter much as you should have one or the other, not both.

In most packages, you will use `find_library` because it will search in a number of paths, which may differ or be updated later. So, better to go with `find_library`.

**Comment by MatthewARM** [comment]
It's quite a high-impact change because it changes the default behaviour. This would change everyone's build and deployment scripts. Is there a way we can move towards it incrementally, without breaking existing workflows?

**Comment by ggardet** [comment]
@MatthewARM  
So, adding `find_library(...)` as in 1st comment (after the ones for static libs) should do the trick. 
Could you test this patch in a static lib environment, please? I know it is working for the shared libs env and I am confident that it will work since `find_lib` will stop searching as soon as a match is found.

**Comment by MatthewARM** [comment]
OK I can try that, will probably have time on Friday.

**Comment by ggardet** [comment]
Any update on this topic?

**Comment by MatthewARM** [comment]
Thanks for the prod, I'll do it now

**Comment by ggardet** [comment]
I think you may also need to change `add_definitions("-DBOOST_ALL_NO_LIB")`  by `add_definitions("-DBOOST_ALL_DYN_LINK")` in `cmake/GlobalConfig.cmake`.

**Comment by MatthewARM** [comment]
I thought I added an option for that a while back

**Comment by ggardet** [comment]
> I thought I added an option for that a while back

Ah, maybe. I may have missed it.

**Comment by ggardet** [comment]
> I thought I added an option for that a while back:
> 
> -DSHARED_BOOST=1

Hmm, it looks like that `add_definitions("-DBOOST_ALL_NO_LIB")` Should be in the else, no?  https://github.com/ARM-software/armnn/blob/8c3259fa007d43fcc5ea56fe6928526dbe79f3c0/cmake/GlobalConfig.cmake#L119

**Comment by MatthewARM** [comment]
No, we need BOOST_ALL_NO_LIB as without it you get Boost's cunning auto-linking thing (#pragma link") which we don't need because we link explicitly to just what we need.

**Comment by MatthewARM** [comment]
Review here: https://review.mlplatform.org/c/ml/armnn/+/2858 I'd appreciate it if you could +1 the review if it works to solve the problem you are seeing

**Comment by ggardet** [comment]
The last update I have is to add `log`and `thread` to the list of boost libraries in `cmake/GlobalConfig.cmake`: 
```
- find_package(Boost 1.59 REQUIRED COMPONENTS unit_test_framework system filesystem program_options)
+ find_package(Boost 1.59 REQUIRED COMPONENTS unit_test_framework system filesystem log thread program_options)
```

**Comment by MatthewARM** [comment]
I don't think we use log and thread directly, so that must mean that FindBoost.cmake isn't correctly determining indirect dependencies. It would be better to fix it in FindBoost.cmake.

**Comment by MatthewARM** [comment]
Oh hang on, we did previously use boost::log - which version of Arm NN are you looking at?

**Comment by ggardet** [comment]
I use `20.02`. `log` is new, but `thread` is there for a while.

**Comment by ggardet** [comment]
Anything I could do to move forward?

**Comment by MatthewARM** [comment]
Thanks @ggardet, if you have time to help we need to figure out:

* If we're using boost::log or boost::thread directly from ArmNN, then they need to be added to the list of boost libraries requested in GlobalConfig.cmake
* If the log and/or thread libraries are needed indirectly by one of the boost libraries that we _are_ using directly, then we need to see if an update to FindBoost.cmake will fix it. FindBoost.cmake is updated in the cmake mainline, but we keep a version of it in Arm NN from recent cmake so that we can continue to build correctly with older cmakes on Linux distributions.

**Comment by ggardet** [comment]
I retried the build (without any downstream patches) and it just passed with armnn 20.02 without adding `log` and `thread` to the list of boost libraries. So, I will close this ticket as all issues are now addressed. 
Thanks!
