### ISSUE TITLE
error while loading shared libraries 

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/armnn#352]
Hello. I have built armnn for quantized mobilenet image classification. But running `./UnitTests` raises the following error:

> error while loading shared libraries: /usr/local/lib/libarmnnTfLiteParser.so.19: unexpected reloc type 0x03

What should I do to resolve the issue?

**Comment by nikraj01** [comment]
Hi @zanazakaryaie ,

What board are you trying to run the Unittest on? Just want bit details about the architecture of the board basically. Also have you tried to use the cross compiling guide that we have here:https://github.com/ARM-software/armnn/blob/branches/armnn_20_02/BuildGuideCrossCompilation.md?

Thanks,
Nikhil.

**Comment by zanazakaryaie** [comment]
Hi @nikraj01 
I'm using Odroid-XU4 with Ubuntu Mate 18.04
I have not yet tried cross-compilation. I used the tutorial here: 
https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow-lite/single-page

**Comment by nikraj01** [comment]
Hi @zanazakaryaie ,

Can you try the following:

While building flatbuffer:
cd $BASEDIR/flatbuffers
mkdir build_arm
cd build_arm
apt-get install cmake
CC=/usr/bin/arm-linux-gnueabihf-gcc \
CXX=/usr/bin/arm-linux-gnueabihf-g++ \
cmake .. \
-G "Unix Makefiles" \
-DCMAKE_BUILD_TYPE=Release \
-DFLATBUFFERS_BUILD_TESTS=0 \
-DCMAKE_INSTALL_PREFIX:PATH=$BASEDIR/flatbuffer_install_arm
make install


Then try to generate tflite schema manually using flatbuffer:

cd $<your_base_directory>
mkdir tflite_generated
cd tflite_generated
cp <your_directory>/tensorflow/tensorflow/lite/schema/schema.fbs .
../flatbuffers/build_x86_64/flatc -c --gen-object-api --reflect-types --reflect-names schema.fbs

and while building ArmNN use the following flags :
-DFLATBUFFERS_ROOT=$BASEDIR/flatbuffer_install_arm \
-DTF_LITE_GENERATED_PATH=$BASEDIR/tflite_generated 

instead of:
-DTF_LITE_GENERATED_PATH=$BASEDIR/tensorflow/tensorflow/lite/schema

Also can you please let me know what versions of flatbuffer and protobuf are you using?

And just making sure are you using ArmNN 20.02?

Thanks,
Nikhil.

**Comment by zanazakaryaie** [comment]
Hi @nikraj01 
Thanks for the reply

How can I see the versions of flatbuffer, protobuf and ArmNN? I'm using the latest versions cloned from their github repo.

Let me do the instructions you mentioned and see if it resolves the issue or not.

**Comment by zanazakaryaie** [comment]
@nikraj01 
You mentioned this to generate tflite schema manually using flatbuffer:

```
cp <your_directory>/tensorflow/tensorflow/lite/schema/schema.fbs .
../flatbuffers/build_x86_64/flatc -c --gen-object-api --reflect-types --reflect-names schema.fbs
```
BUT, there is no `lite` directory in my `tensorflow` directory!

**Comment by nikraj01** [comment]
Hi @zanazakaryaie ,

We are using TF version 1.15, so if you go to the section "Setup and download libraries" in the guide it says to checkout a particular revision of TF. We are on 3.5.0 for protobuf - this is mentioned in the "Build the Google protobuf Library" section. Could you please try with those versions and let me know.

Latest version of ArmNN is 20.02 :)

Thanks,
Nikhil.

**Comment by nikraj01** [comment]
Hi @zanazakaryaie ,

Were you able to build things properly? Wondering if this ticket can be closed then?

Thanks,
Nikhil.

**Comment by ome61952** [comment]
@zanazakaryaie were you able to fix this issue with @nikraj01  solution. Seems like you have built successfully, I am facing same issue. Can you please let us know the steps you used to solve this issue

**Comment by zanazakaryaie** [comment]
@nikraj01 @ome61952 
Yes, I resolved the issue by moving to Raspberry Pi. Odroid XU4 has 32bit CPU and is not good for testing armnn. So I moved to a Raspberry Pi and installed a 64bit OS (Ubuntu Mate). Then followed the armnn tutorials. After building the library, there were some warnings when running ./UnitTests, but I could run the Mobilenet SSD Lite on an image with 6 FPS approximately.

**Comment by ome61952** [comment]
@zanazakaryaie  That's great news. 
I also managed to solve this issue on 32-bit ARMv7 Processor on Tinkerboard S using the recommendation from https://github.com/ARM-software/armnn/issues/158. 

I am trying to build a Resnet50 based face recognizer and it is extremely slow on GPU and NEON around ~700-900ms per frame.  Do you think moving to 64bit processor will help?

**Comment by zanazakaryaie** [comment]
@ome61952 Yes I think. Check #362 

Tensorflow itself is also optimized for 64bit OS.

**Comment by james-conroy-arm** [comment]
Hi @ome61952 ,

Do you have any other questions regarding this issue? Otherwise, could you close it please?

Cheers,
James

**Comment by james-conroy-arm** [comment]
Hi @zanazakaryaie , @ome61952 ,

I'm going to close this issue now as it looks like it is resolved.

Please feel free to comment here if the issue persists.

Cheers,
James
