### ISSUE TITLE
DCGAN parsing failed at function ParseConcat

### ISSUE THREAD

**Issue by quentiel-09** [ARM-software/armnn#375]
Hello,
I'm trying to write an application to run inference using a DCGAN TensorFlow model. This model needs 2 inputs of shapes (64, 100) and (64, 10). When I parse the model, I have an error at the function ParseConcat and I don't understand how to get rid of it...

The beginning of my code is:
```cpp
int main(int argc, char *argv[])
{
    auto totalTimeStart = std::chrono::system_clock::now();   
        auto start = std::chrono::system_clock::now();

    /* Import the TensorFlow model */   

    armnnTfParser::ITfParserPtr
        parser = armnnTfParser::ITfParser::Create();
    armnn::INetworkPtr
        network = parser->CreateNetworkFromBinaryFile(TENSOR_MODEL, { {"z", {64,100}},{"y", {64, 10}} }, { "generator_1/Sigmoid"});
```
It compiles but when I run it, I have the following error:
**terminate called after throwing a[ 3538.454454] audit: type=1701 audit(1586852937.907:17): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=871 comm="dcgan_inference" exe="/home/root/dcgan/dcgan_inference" sig=6 1
n instance of 'armnn::ParseException'
  what():  The number of dimensions: 2 for input tensors of the concatenation op should be 4  at function ParseConcat [/usr/src/debug/armnn/19.08-r1/git/src/armnnTfParser/TfParser.cpp:2115]
Aborted**

I also tried to use the input format { {"z", {1, 100, 64,1}},{"y", {1, 10, 64, 1}} } to follow the NHWC format, but I obtained the same result..

For info, the first part of my network is:
![image](https://user-images.githubusercontent.com/63638605/79206952-5c506200-7e40-11ea-8f27-e2a72043f793.png)

Could you help me understand what is wrong ?
Thank a lot in advance

**Comment by MikeJKelly** [comment]
Hi @quentiel-09 

from looking at the code I can see that this restriction is only on the TensorFlow parser not the TensorFlow Lite parser, can you convert your model to a TF Lite model and try that parser?

Best regards,
Mike

**Comment by MikeJKelly** [comment]
It could be alright, if an operator is missing then the resulting model will probably be malformed... an alternative would be to simply disable the error in the TFParser and see if that works? 

Can you provide the tf model?

**Comment by quentiel-09** [comment]
I used this project: https://github.com/carpedm20/DCGAN-tensorflow
DCGAN are made from two models trained simultaneously by an adversarial process, but I only froze one of the model which is called the "generator". To do so I used "generator_1/Sigmoid" as the output_node_names during the frozen process in order to obtain my model.pb .

**Comment by matthewsloyanARM** [comment]
Hi @quentiel-09,

Unfortunately with the upcoming Arm NN release (21.05) we will be deprecating the Arm NN TF Parser, so we won't be able to make any additions to this in regard to adding operator support. You had tried the TFLite Parser though, would you be able to supply the TFLite model so we could take a look? It is quite possibly as mentioned before that a operator or parameter used by the converter isn't supported in the TFLite Parser. What I can also recommend is the Arm NN TFLite Delegate. This plugs into the TFLite Interpreter and provides a greater operator range as if it's not supported in Arm NN the layer will fallback to the TFLite default implementation rather than exiting like the TFLite Parser. A guide to implement your own application can be found [here](https://arm-software.github.io/armnn/latest/md_delegate__build_guide_native.xhtml).

Also based on the updated `README.md` found [here](https://github.com/ARM-software/armnn/tree/master#how-to-get-involved) under the "How to get involved" section I will close this issue as it is labeled with "Feature Request". Instead, we will be tracking the issue and adding the "Help wanted" label. All the issues with this label can be found [here](https://github.com/ARM-software/armnn/issues?q=is%3Aissue+label%3A%22Help+wanted%22+). As this is an old issue would you be able to let us know with a quick comment that you are still interested in finding a solution to your problem, if so feel free to reopen this ticket. Thank you!

Kind regards,

Matthew
