### ISSUE TITLE
[TfLite Quant] CpuAcc outputs different value to CpuRef during inference

### ISSUE THREAD

**Issue by choice17** [ARM-software/armnn#396]
Hi,

I tried to implement mtcnn(tflite quant version) with armnn. And I implemented Prelu activation using NEG ops in tensorflow lite.
Refer to https://github.com/ARM-software/ML-examples/tree/master/armnn-mobilenet-quant project. I can now compile and load/run network. However the result from runtime option "CpuAcc" give different result to "CpuRef".

Refer to https://github.com/ARM-software/armnn/issues/97#issuecomment-436262276
> CpuAcc backend should give the same result as the CpuRef backend, unless there is a bug. 

Here are the two heat maps generated by CpuRef(Left) and CpuAcc(Right) runtime option.
![pnet_cpuref](https://user-images.githubusercontent.com/25946145/83737891-3304c300-a686-11ea-9d8a-11bdb9916267.jpg)  ![pnet_cpuacc](https://user-images.githubusercontent.com/25946145/83737937-4152df00-a686-11ea-9f7f-0051c1f3afc7.jpg)

The exact outputs and source code are included in the zip file for reproduction.

Environ.
Ubuntu 16.04 LTS
Cross compiler arm-linux-gnueabihf-
armnn 20.05 (cherry-pick 0ae06d9d9f0 for NEG operator support)
computelibrary 20.05

[pnet_quant_tflite_proj.zip](https://github.com/ARM-software/armnn/files/4728897/pnet_quant_tflite_proj.zip)

**Comment by MatthewARM** [comment]
Heh, I do remember saying that on #97 back in 2018. Sadly it's not true any more - the TfLite quantisation scheme has completely changed, which we really had to follow so that we could continue to be a drop-in replacement for TfLite. Meanwhile the CpuRef backend was getting almost as complicated as the accelerated backends, so it was losing its purpose as a reference for how operators were supposed to work. 

These days you should consider the TfLite runtime to be the de-facto reference for quantised ops, as that implementation feeds the NNAPI implementation, which defines the conformance tests that Arm NN has to pass for Android compliance. 

The Arm NN CpuRef backend also passes the Android conformance tests but each individual layer may differ by a value of 1 in the quantized payload, which is the tolerance permitted by the Android tests.

For what it's worth, it's not an issue unique to Arm NN. See also https://github.com/tensorflow/tensorflow/issues/38845

**Comment by choice17** [comment]
@MatthewARM , is that true for floating point inference (CpuAcc vs CpuRef) ? As I observe subtle differences between CpuAcc and CpuRef using CaffeParser floating point model.

**Comment by MatthewARM** [comment]
For floating point the numbers should be identical _except_ for 3x3 convolution where the Compute Library may choose to use a Winograd implementation (for speed) instead of GEMM. That has the same mathematical definition but performs the floating-point multiply-accumulates in a different order so rounding errors may accumulate differently.

The corresponding documentation in Compute Library is here: https://arm-software.github.io/ComputeLibrary/v20.05/classarm__compute_1_1_n_e_convolution_layer.xhtml

You can confirm which layer is causing differences by enabling 'debug' in OptimiserOptions and registering a debug callback to dump the intermediate tensors in the model. If you're interested I can dig out a documentation reference for that?

**Comment by choice17** [comment]
@MatthewARM, thanks again for the quick reply. It would be great to have the debug documentation reference.

**Comment by choice17** [comment]
I will just close this issue as it seems there is no way to give identical result between CpuAcc backend and CpuRef backend in some cases.

Summary.
1. For quantization inference,  tflite CpuAcc backend gives the similar but not equal result as the CpuRef backend for quantization inference.
2. For floating point inference, CpuAcc backend may gives the similar but not equal result as the CpuRef backend when networks are using 3x3 convolution
