### ISSUE TITLE
Subtraction Operator Outputs Wrong Result While Using TFLite Model

### ISSUE THREAD

**Issue by XiaoxingChen** [ARM-software/armnn#418]
Hi there, 
    I'm using ARMNN 20.05, android-ndk-r20b-linux-x86_64, with API 21.
    I found the output of subtraction operator giving me wrong result while using tflite model. I will show you in a toy example:

![subtraction](https://user-images.githubusercontent.com/16934019/86574642-b9bfff00-bfa8-11ea-979c-65436d81362d.png)
I build a tensorflow lite model with subtraction operator only, the model does one thing: f(x) = x - 1. However, the result I got was: f(x) = 1-x. Could you please kindly check the tflite parser to see whether there are some issues? I'll attach my toy project below. There is a readme.md in the compressed file, showing how to compile and test.

[armnn_sub_sample.zip](https://github.com/ARM-software/armnn/files/4877799/armnn_sub_sample.zip)

**Comment by james-conroy-arm** [comment]
Hi @XiaoxingChen ,

Thanks for reporting this issue. We are investigating it now.

Cheers,
James

**Comment by MikeJKelly** [comment]
Hi @XiaoxingChen 

Thank you for the report and the example, this reveals a defect in the way we handle Broadcasting in all TFLite operations. When we have to Broadcast a Tensor for an operation we put in a Reshape for the smaller Tensor (in this case input B) but due to a bug in our code the reshaped Tensor was always connected to the first input and the non-reshaped Tensor to the second input. In this case it reversed the operand order for the operation changing it from A - B to B - A. 

I've fixed the issue so we remember the correct order for the inputs. The code for the fix is at:

https://review.mlplatform.org/c/ml/armnn/+/3515 

It should be merged in the next day or so. 

Best regards,
Mike

**Comment by james-conroy-arm** [comment]
Hi @XiaoxingChen ,

@MikeJKelly 's patch has now merged. Please let us know if this resolves your issue.

Cheers,
James

**Comment by XiaoxingChen** [comment]
Hi @james-conroy-arm and @MikeJKelly ,
    Thank you for your fast response, the patch works!

Best!
Xiaoxing.

**Comment by james-conroy-arm** [comment]
Glad to help!

Please let us know if we can close this issue, if you don't have any other questions relating to this.

Cheers,
James

**Comment by XiaoxingChen** [comment]
Yes, James, please close it. Appreciate your efforts!
