### ISSUE TITLE
Getting Error while ArmNN Cross Compilation

### ISSUE THREAD

**Issue by paragikjain** [ARM-software/armnn#450]
Hi Team,

I am getting Below error in Cmake of armNN  cross compilation for yocto

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CXXOPTS_INCLUDE

@MatthewARM 

Thanks for Help in Advance

**Comment by FinnWilliamsArm** [comment]
Hi paragikjain,

That's a third party library we use to replace boost program options.
Could you please check that cxxopts.hpp exits in third-party/cxxopts?

Another possibility is that you are building with BUILD_PIPE_ONLY enabled, in which case the path would not be set.

Thanks 

Finn

**Comment by paragikjain** [comment]
HI Finn
Thanks for the help 

That header file is present in my case and the path is also added to cmake file and I am not using BUILD_PIPE_ONLY mode.
Still getting the same error

**Comment by paragikjain** [comment]
Hi Finn I have checked out older version of git and now that error has gone previously i was using 20 now i have checkout 18

**Comment by vinceab** [comment]
Hi @Finn, 

Is it planned to replace boost options by cxxopts?
Because it creates for Yocto project build system an unmet dependency to cxxopts.
Most of the armnn test are using boost options.
Why only ./TfLiteYoloV3Big-Armnn/TfLiteYoloV3Big-Armnn.cpp is using cxxopts?
Why can't we simply keep boost options which is already supported by the yocto build system?

Solution of @paragikjain is to checkout older version but it can't be the solution.

Thanks
Vincent

**Comment by FinnWilliamsArm** [comment]
Hi @vinceab 

Apologies missed this due to the issue being closed.

Yes Arm NN is going to remove all boost dependencies, we are currently in the process of phasing it out.
We are doing this due to a requirement from some of our partners.
If you have any issues with this please contact me and I will forward them on.

Thanks 

Finn

**Comment by vinceab** [comment]
Hi @FinnWilliamsArm ,

I have pushed a gerrit patch that fixe the issue for YOCTO build:
https://review.mlplatform.org/c/ml/armnn/+/3906

Vincent

**Comment by FinnWilliamsArm** [comment]
Hey @vinceab 

Oh that's great, thank you very much!

Finn
