### ISSUE TITLE
Wrong output shape inferred for SpaceToBatchNd

### ISSUE THREAD

**Issue by r-czarnecki** [ARM-software/armnn#455]
Hi, I'm trying to run a tflite model that consists of SpaceToBatchNd operation. For now, the code I'm running is:
```
armnn::ConfigureLogging(true, false, LogSeverity::Warning);
armnn::NetworkId networkIdentifier;
armnnTfLiteParser::ITfLiteParserPtr parser = armnnTfLiteParser::ITfLiteParser::Create();

INetworkPtr myNetwork = parser->CreateNetworkFromBinaryFile("model.tflite");

armnnTfLiteParser::BindingPointInfo inputBindingInfo = parser->GetNetworkInputBindingInfo(0, "input_name");
armnnTfLiteParser::BindingPointInfo outputBindingInfo = parser->GetNetworkOutputBindingInfo(0, "output_name");

IRuntime::CreationOptions options;
IRuntimePtr run = IRuntime::Create(options);

armnn::IOptimizedNetworkPtr optNet = Optimize(*myNetwork, {Compute::CpuRef}, run->GetDeviceSpec());
```

Unfortunately Optimize function gives me this exception:
```
terminate called after throwing an instance of 'armnn::LayerValidationException'
  what():  SpaceToBatchNdLayer: TensorShape set on OutputSlot[0] does not match the inferred shape. : [3,520,192] != [3,520,51745]
Aborted (core dumped)
```
What is strange, the last dimension of the inferred shape is always different every time I rerun the program.

I was able to reproduce the issue with tflite model consisting of only two operations: ReLU -> SpaceToBatchNd

Is this a bug or am I doing something wrong?
Thanks

**Comment by MikeJKelly** [comment]
Hi @r-czarnecki 

I think there are two possible issues that could cause this.

First, the fact that the last dimension is different every time may might indicate that one of the other variables in your model is being left uninitialised. If that's the case then we could get random values when inferring the output shape. The output shape height and width dimensions are calculated using the input shape's width or width, the padding and the height or width of the blockShape, if any of these are undefined you might have this issue.

Second, there is currently a limitation in ArmNN where most of our layers including SpaceToBatchNd can only accept a 4 dimensional shape with either an NCHW or NHWC data layout (NHWC by default). You've given a 3 dimensional shape which may be confusing the outputshape calculation to change this to a four dimensional shape you could put it in as [3,520,192,1] and it should behave the same as [3,520,192]. 

If that doesn't work then can you share your model? 

Best regards,
Mike

**Comment by r-czarnecki** [comment]
I have tried to use the 4 dimensional input and it solves the problem with the wrong output shape. Unfortunately now I get `Floating point exception (core dumped)` whenever I run the `Optimize` function. 

[This](https://github.com/ARM-software/armnn/files/5237468/test.tflite.zip) is the model that causes this error. I use the same code as described in my first post to run it.

**Comment by MikeJKelly** [comment]
Hi @r-czarnecki 

Thanks for sharing the model, I ran it through the parser and I get the same error you originally posted (something like ```TensorShape set on OutputSlot[0] does not match the inferred shape. : [3,520,192,1] != [3,520,59523,1]```) so I still see the random 3rd dimension. 

Looking at the model I can see that the blockshape only has a single dimension with a value of [3]. According to the TfLite specification (https://www.tensorflow.org/api_docs/python/tf/space_to_batch) it should have the same number of dimensions as the spatial shape of the input tensor (i.e. it should have a height and width) so we'd expect a 2-dimensional blockshape, like [3,3]. 

Currently, the code we have doesn't check the length of the blockshape vector it just get's the 0th entry for the height and the 1st entry for the width, in this case the width could be anything as it's just the next piece of memory after the blockshape vector. I'll fix that so that it throws a more useful exception in future. 

Can you please check if setting a 2-dimensional blockshape fixes your issues?

Best regards,
Mike

**Comment by r-czarnecki** [comment]
I've changed the model to use 4-dimensional input and 2-dimensional blockshape and it seem to be working fine now. Thank you for the help.
