### ISSUE TITLE
[Contribution issue] inconvenient ARMNN contribution process for contributers.

### ISSUE THREAD

**Issue by daeinki** [ARM-software/armnn#492]
Hello ARM engineers.

I'm an newbie attending ARMNN and ARMCL open source projects.
Until now, I have contributed several patches to ARMNN and even to ARMCL.
And recently, I have posted a new patch set[1] to ARMNN but the gerrit review system on mlplatform.org is making me confusing.

The contribution guide on https://www.mlplatform.org/contributing says,
```
Continuous Integration
Contributions to machine learning platform codebases go through testing at the Arm CI system. All unit, integration and regression tests must pass before a contribution will be merged to a repository’s master branch.
```

Yes, posted patch/s from contributors should be reviewed by reviewers and tested at ARM CI system. However, when build error happens, there is no way for contributors to check for the error - impossible to access to https://cvbuilder.ml.arm.com.

If ARM cannot allow contributors to access to the CI system then I think at least someone(one of ARM engineers) need to give  contributors some guide as comment so that the contributors can keep going on their contributions.

Contributors never know what happens in CI system. Otherwise, Is there any process I'm missing to access the system?

[1] https://review.mlplatform.org/c/ml/armnn/+/4742

**Comment by MatthewARM** [comment]
Yes, this is a big problem. 

Most of the build and test systems for Arm NN are still hosted within Arm, and for security reasons Arm can't approve non-Arm employees to run code within their network.

There is supposed to be a second, more publicly accessible, build system running in Linaro that also builds and tests the code, but it's broken at the moment. I'll chase up that.

I'd like to set up a capable build and test system that's completely publicly accessible but it seems quite hard (time consuming and expensive), mainly because running all the Android NNAPI tests on every build requires specialised infrastructure.

In the meantime, you're doing the right thing - one of the Arm employees on the team needs to trigger the build, and find out why it failed, to let you know  :-(

We should document this more clearly in the contributor guide.

**Comment by K1504296** [comment]
Hey daeinki, 

The Linaro CI was mistakenly set to silent mode due to previous errors which have since been resolved. This is fixed now so any patches should get a corresponding update in the mlplatform gerrit comments. 

Looking back through the Jenkins Job history patch set 5 is the most recent one I can find, it's possible it's backlogged and newer ones haven't started yet.

Here's patchset 5 if that is still useful for you : https://ci.linaro.org/job/armnn-ci-build/3929/

Sorry for the inconvenience,
Theodore Grey

**Comment by daeinki** [comment]
> Hey daeinki,
> 
> The Linaro CI was mistakenly set to silent mode due to previous errors which have since been resolved. This is fixed now so any patches should get a corresponding update in the mlplatform gerrit comments.
> 
> Looking back through the Jenkins Job history patch set 5 is the most recent one I can find, it's possible it's backlogged and newer ones haven't started yet.
> 
> Here's patchset 5 if that is still useful for you : https://ci.linaro.org/job/armnn-ci-build/3929/
> 
> Sorry for the inconvenience,
> Theodore Grey

With above link, I could check for the build problem to my patch.

Thanks for fixing it up,
Inki Dae

**Comment by FrancisMurtagh-arm** [comment]
Hi @daeinki,

I have requested updates to the guide https://www.mlplatform.org/contributing to make it more clear for future contributors.

Thanks for your patch I see it has since been merged.
Francis.
