### ISSUE TITLE
3 UnitTests failures with 'check timelineDecoder.GetModel()' on version 21.02

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#529]
While updating to version 21.02, I have 3 UnitTest failures:
```
[ 2795s] + ./build/UnitTests
[ 2821s] Running 3609 test cases...
[ 2821s] /home/abuild/rpmbuild/BUILD/armnn-21.02/tests/profiling/gatordmock/tests/GatordMockTests.cpp(488): [1;31;49merror: in "GatordMockTests/GatorDMockTimeLineActivation": check timelineDecoder.GetModel().m_Entities.size() == 6 has failed[0;39;49m
[ 2821s] /home/abuild/rpmbuild/BUILD/armnn-21.02/tests/profiling/gatordmock/tests/GatordMockTests.cpp(490): [1;31;49merror: in "GatordMockTests/GatorDMockTimeLineActivation": check timelineDecoder.GetModel().m_Labels.size() == 34 has failed[0;39;49m
[ 2821s] /home/abuild/rpmbuild/BUILD/armnn-21.02/tests/profiling/gatordmock/tests/GatordMockTests.cpp(491): [1;31;49merror: in "GatordMockTests/GatorDMockTimeLineActivation": check timelineDecoder.GetModel().m_Relationships.size() == 15 has failed[0;39;49m
[ 2835s] 
[ 2835s] [1;31;49m*** 3 failures are detected in the test module "UnitTests"
```

**Comment by matthewsloyanARM** [comment]
Hi @ggardet, 

Thank you for reaching out. Have you changed any build parameters since you last updated the version?

Kind regards,

Matthew

**Comment by ggardet** [comment]
@matthewsloyanARM No changes regarding the build config. I just updated Arm Compute library and ArmNN.

**Comment by matthewsloyanARM** [comment]
@ggardet Okay thank you for letting me know, I am looking into this for you.

Kind regards,

Matthew

**Comment by matthewsloyanARM** [comment]
Hi @ggardet,

I haven't been able to recreate these unit test failures with Arm Compute library and ArmNN version 21.02. Are these failures consistent or did they only occur once? These tests could possibly fail randomly due to threading and socket issues.

Another possibility is that there could be a mix-up of the profiling libraries being used. In the 21.02 release we added versioning to the libtimelineDecoder, libtimelineDecoderJson and libarmnnBasePipeServer, so it could be possibly be using an old library. For example in the build directory there will be a libtimelineDecoder.so, libtimelineDecoder.so.24 and libtimelineDecoder.so.24.0. Would you be able to check this? Thank you!

Kind regards,

Matthew

**Comment by ggardet** [comment]
This is in the build system for openSUSE (Tumbleweed), so all builds start from a clean directory and isolated in a qemu VM, so no risk to have some old libs.
The problem seems to be gone now, so no idea what could have caused this and what fixed it...

**Comment by matthewsloyanARM** [comment]
That is interesting to know. Thank you for testing this out again, sometimes issues like this can be intermittent but I am happy to hear it has been resolved.

Kind regards,

Matthew
