### ISSUE TITLE
High Network loading times

### ISSUE THREAD

**Issue by prabhakarlad** [ARM-software/armnn#530]
Hi All,

When using the GPU (MALI-Gx) as a backend we are seeing high network loading times when compared to CPU(aarch64 dual core) as a backend.

Using ExecuteNetwork to profile the CPU and GPU backends for profiling,
`./ExecuteNetwork -c GpuAcc -f tensorflow-binary -m /home/root/models/tensorflow/inception_v3_2016_08_28_frozen.pb -i input -o InceptionV3/Predictions/Reshape_1  -s 1,299,299,3 -e > gpu.txt`
`./ExecuteNetwork -c CpuAcc -f tensorflow-binary -m /home/root/models/tensorflow/inception_v3_2016_08_28_frozen.pb -i input -o InceptionV3/Predictions/Reshape_1  -s 1,299,299,3 -e > cpu.txt`

Comparing the logs attached below, the memory operations when using GPU as backend is taking more time when compared to CPU backends.

* Is there anything I am missing here/doing silly ?
* Are there any other possible options where the times can be reduced ?
* Are there any good references on how memory is handled when using OpenCL , and can be optimized ?

options tried:
* Tuner file option [1] and saw no improvements either.
* Converting the model to armnn using ArmConverter and re-running the tests (no difference)

[profile_cpu.txt](https://github.com/ARM-software/armnn/files/6235935/profile_cpu.txt)
[profile_gpu.txt](https://github.com/ARM-software/armnn/files/6235936/profile_gpu.txt)

[1] https://community.arm.com/developer/ip-products/processors/b/ml-ip-blog/posts/arm-nn-gpu-inference-with-opencl-tuner

Cheers,
Prabhakar

**Comment by matthewsloyanARM** [comment]
Hi @prabhakarlad,

That is probably due to the time it takes compile OpenCL kernels. In the 21.02 release a feature was added to cache the compiled kernels and reload them on subsequent runs. Using ExecuteNetwork if you specify `--save-cached-network --cached-network-filepath <path_to_file>` this will create a cache of the compiled kernel in the file `<path_to_file>`. Then on subsequent runs if you just use `--cached-network-filepath <path_to_file>` and remove the `--save-cached-network` parameter the kernels will be reloaded from the cache file you specified and the re-compilation will be avoided. Would you be able to try this out and see if it helps?

If you have any further questions feel free to reach out. Thank you!

Kind regards,

Matthew

**Comment by prabhakarlad** [comment]
Hi @MatthewARM,

Not sure if this is a bug or I am doing this wrong, I tried the below two commands and none of them saved the cached network file.

`./ExecuteNetwork -c GpuAcc -f tensorflow-binary -m /home/root/models/tensorflow/inception_v3_2016_08_28_frozen.pb -i input -o
InceptionV3/Predictions/Reshape_1 -s 1,299,299,3 --save-cached-network --cached-network-filepath /usr/bin/armnn-21.02/examples/ExecuteNetwork/cache.txt`

`./ExecuteNetwork -c GpuAcc -f tensorflow-binary -m /home/root/models/tensorflow/inception_v3_2016_08_28_frozen.pb -i input -o InceptionV3/Predictions/Reshape_1 -s 1,299,299,3 --save-cached-network --cached-network-filepath=/usr/bin/armnn-21.02/examples/ExecuteNetwork/cache.txt`

Is there i am missing something here ?

Cheers,
Prabhakar

**Comment by MatthewARM** [comment]
The problem might be because you don't have permission to write to /usr/bin?  Something like your home directory or a tmp directory would be better.

The first thing to check about the GPU performance is, on your chip how powerful is the GPU compared to the CPU? I often find that on low-end mobile-class chips the CPU is more powerful, whereas at the very high end the GPU is more powerful.

**Comment by matthewsloyanARM** [comment]
Thanks @MatthewARM for your reply. @prabhakarlad To follow up on this another issue could be is that to save a cached network a file must exist to write to. An empty file can be created with `touch cache.bin` for example, but the permissions issue that Matthew mentioned is a good point too. This is mentioned in the help (`--help`) section for that parameter `To save the cached network a file must already exist`.

The `--help` parameter when running ExecuteNetwork also reveals some of the other optimization options available which might be useful. This can be found in section `c) Optimization options:`. Thanks!

Kind regards,

Matthew

**Comment by prabhakarlad** [comment]
Hi @MatthewARM, @matthewsloyanARM,

Creating a file cache.bin (touch cach.bin) and then using option "--save-cached-network --cached-network-filepath cache.bin" did the trick. I can see a improved performance for network loading times now, thanks for that.

I will try the --fp16-turbo-mode/fast math/tune  optimizations options. Thanks for the pointer to [1].

I am doing benchmarks on MALI G31 are there any benchmark results to compare against with ?

[1] https://www.tensorflow.org/model_optimization

Cheers,
Prabhakar

**Comment by prabhakarlad** [comment]
Thanks  for the update @matthewsloyanARM.

**Comment by matthewsloyanARM** [comment]
I am closing this issue as it has been resolved. If you have any questions feel free to reopen this issue or create a new one. Thanks again!
