### ISSUE TITLE
High buffer synchronizing times

### ISSUE THREAD

**Issue by prabhakarlad** [ARM-software/armnn#532]
Hi,

I am seeing high inference times due to time taken for synchronizing buffer as seen in the attached log. This happens when the  network is run on GPU I don't see this issue when run on CPU. In the backend it uses memcpy for both CPU and GPU backends to copy the tensors.

Correct me if my understating is  wrong here, for the GPU backend the buffers are allocated with CL_MEM_ALLOC_HOST_PTR ?
Is there anything I am missing here? Ideally I would expect the memcpy to be roughly same.

For example with mali_cl_svm_cache_perf_example:
mali_cl_svm_cache_perf_example
Buffer size:             64 MB
Number of iterations:    100
Filter:

Coarse grained buffer SVM : Yes
Fine grained buffer SVM   : No
Fine grained system SVM   : No
Atomics SVM               : No

Test case                      Total time(ms)   GPU time(ms)   CPU time(ms)   Cache+Runtime(ms)
BUFFERS NO_HOST_FLAGS                17604.35        8081.47        8155.25             1367.62
BUFFERS USE_HOST_PTR                 28221.49        8127.46        8182.68            11911.35
BUFFERS USE_HOST_PTR (aligned)       28363.92        8147.56        8237.01            11979.34
BUFFERS COPY_HOST_PTR                17555.15        8045.74        8236.97             1272.43
BUFFERS ALLOC_HOST_PTR               17570.21        8035.72        8263.23             1271.26
COARSE GRAIN                         17563.58        8077.93        8258.59             1227.07

[gpu_profile.txt](https://github.com/ARM-software/armnn/files/6278100/gpu_profile.txt)

Cheers,
Prabhakar

**Comment by MikeJKelly** [comment]
Hi @prabhakarlad 

The long sync time is due to the way that the GPU backend works. 

When the network is run on the GPU it schedules work to be done, effectively creating a queue of kernels to execute on the GPU. The GPU then runs all the kernels and returns at the end. The time spent in the sync is the time spent waiting for those kernels to complete. 

The time spent actually copying the memory is a tiny fraction of the sync time. 

Best regards,
Mike.

**Comment by prabhakarlad** [comment]
Hi @MikeJKelly,

Thank you for clarifying, now it makes sense. 

Cheers,
Prabhakar
