### ISSUE TITLE
Install on Debian(ARM64)

### ISSUE THREAD

**Issue by shaojun** [ARM-software/armnn#588]
I'm following the steps on my Debian ARM64 board:

```
sudo apt install software-properties-common
sudo add-apt-repository ppa:armnn/ppa
sudo apt update
```

always failed with 

> E: The repository 'http://ppa.launchpad.net/armnn/ppa/ubuntu impish Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.

is this the reason that `armnn` does not support **Debian ARM64**? or other suggestion?

**Comment by shaojun** [comment]
this is my system info:

> cat /etc/os-release
> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> NAME="Debian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
>

**Comment by FrancisMurtagh-arm** [comment]
Hi @shaojun,

If you want to crosscompile for Debian ARM64 you can follow:
https://github.com/ARM-software/armnn/blob/branches/armnn_21_08/BuildGuideCrossCompilation.md

The 20.08 release of ArmNN is in the Debian Archive for Bullseye, we are planning to upload the latest release to Debian Testing/Bookworm soon but it will take some time for it to be accepted.
https://packages.debian.org/source/bullseye/armnn

You could also add-apt-repository ppa:armnn/ppa to the Debian 11 Bullseye board and then edit the /etc/apt/sources.list of the board so that the suite for the armnn ppa is focal. That should workaround your error:
"E: The repository 'http://ppa.launchpad.net/armnn/ppa/ubuntu impish Release' does not have a Release file."
Also having `deb [trusted=yes]` at the start of that line will stop the ppa from being disabled:
"N: Updating from such a repository can't be done securely, and is therefore disabled by default."

So your /etc/apt/sources.list file should have a line like this:
`deb [trusted=yes] http://ppa.launchpad.net/armnn/ppa/ubuntu focal main`

This might also be in a file called something like this instead, depending on your distro:
/etc/apt/sources.list.d/armnn-ubuntu-ppa-focal.list

This is a workaround however so be sure to backup or be able to re-flash your board if necessary.

Thanks,
Francis.

**Comment by MikeJKelly** [comment]
Hi @shaojun 

I believe this issue has been resolved so I'm going to close the ticket now if you have any further questions then please open a new issue. Thanks!

Best regards,
Mike
