### ISSUE TITLE
What is the difference between CpuRef and CpuAcc?

### ISSUE THREAD

**Issue by myth01** [ARM-software/armnn#70]
What is the difference between compute device options armnn::Compute::CpuRef and armnn::Compute::CpuAcc?

**Comment by MatthewARM** [comment]
Hi @myth01 , 

CpuAcc or "CPU Accelerated" requires NEON support, so will only work on Cortex-A processors and a subset of Cortex-R processors.

CpuRef or "CPU Reference" is a simple implementation using portable C++. You can use this to run ArmNN on Intel-architecture computers during development of your application. It is not suitable for use in deployed applications because it has poor performance compared to the alternatives.

I hope this answers your question,
Matthew
