### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by sachindia86** [ARM-software/armnn#737]
I am trying to build Compute Library natively on AWS t4g.small(2 Cores) instances based on ARM.

I have used below command to build the library.
scons Werror=1 -j2 debug=0 neon=1 opencl=0 os=linux arch=armv8.6-a build=native standalone=1 logging=1

However while building the examples using the below command
aarch64-linux-gnu-g++ examples/neon_cnn.cpp utils/Utils.cpp -I. -Iinclude -std=c++14 -L. -larm_compute -larm_compute_core -o neon_cnn

I am facing below linker error.

/usr/bin/ld: cannot find -larm_compute: No such file or directory
/usr/bin/ld: cannot find -larm_compute_core: No such file or directory
collect2: error: ld returned 1 exit status

Please help to resolve the issue.

**Comment by nikraj01** [comment]
Hi @sachindia86 ,

Thanks for raising the issue. Would you mind raising the issue in here https://github.com/ARM-software/ComputeLibrary/issues please as its unrelated to ArmNN.

Thanks

**Comment by morgolock** [comment]
Hi @sachindia86 

It looks like the problem is that the linker cannot find `libarm_compute.so`. 

Please try building the library without `standalone=1` as this is meant for internal use only. The purpose of `standalone=1` is to build the test suite as a standalone binary that does not need any shared libraries to run.

Once you built the library you can build the example but make sure you use `-L./build` which is the correct path to the folder containing the shared libraries you need the example to link with.
`arch64-linux-gnu-g++ examples/neon_cnn.cpp utils/Utils.cpp -I. -Iinclude -std=c++14 -L./build/ -larm_compute -larm_compute_core -o neon_cnn`

Hope this helps.

**Comment by morgolock** [comment]
Closed by inactivity, if you still require help please reopen.
