### ISSUE TITLE
Arm NN Build Tool does not support 32-bit ARM v7

### ISSUE THREAD

**Issue by robertbcalhoun** [ARM-software/armnn#779]
ARM Compute Library supports ARM v7, so ARM NN should support ARM v7. Previous issue #29 states that 32-bit arm is supported.

Running build tool with `--target-arch=arm` fails with:

```
 > [final 3/3] RUN ./build-armnn.sh --target-arch=arm --onnx-parser --neon-backend:
0.326 build-armnn.sh: --target_arch is not valid. Valid options are: aarch64, android64, x86_64
```

I haven't tried the direct build using cmake yet. I am still working on the port to buildroot for aarch64.

**Comment by Colm-in-Arm** [comment]
Hi Robert.

You are correct. The Build tool does not support armv7 targets. However, you "should" be able to natively build for armv7. This was previously something we built on a nightly basis until the 22.08 release. There may have been incompatible changes made since then. If you encounter any please let us know and we can see if provide some fixes for you.

Colm.
