### ISSUE TITLE
Winograd based convolution

### ISSUE THREAD

**Issue by ddenaro** [ARM-software/armnn#87]
Hi,
Could you explain in which way ArmNN decide to use the convolution method winograd or GEMM ?
Is It possible to pass this hit to the network optimizer ?

**Comment by MatthewARM** [comment]
Hi @ddenaro ArmNN just calls the Compute Library 'ConvolutionLayer' function, and lets Compute Library make the decision. I believe that by default this will generally use Winograd for 3x3 FP32 kernels only, because the Winograd method produces different results than the spatial method in other cases.
The Compute Library exposes an option to allow Winograd in other cases, but this is not set by ArmNN at the moment. We are trying to decide on a good way to do this. An option on the optimiser seems sensible and it might also be needed on IsConvolutionLayerSupported.

If you would like to try setting the flag, the documentation is here: https://arm-software.github.io/ComputeLibrary/v18.08/classarm__compute_1_1_c_l_convolution_layer.xhtml#ae0c61dabbcfeda5c7f01a7ae66e58b2c see the `enable_fast_math` parameter. With the flag set, Compute Library (and ArmNN) may not return the exact same results from Convolution as your model was trained with, so it may return different outputs than you expect.

**Comment by ddenaro** [comment]
Ok, thank you
