### ISSUE TITLE
ARM-NN profiling

### ISSUE THREAD

**Issue by xiaomin05** [ARM-software/armnn#94]
How do I enable ARM -NN profiling?
When "-e 1" is specified while running TfMobileNet, no profiling result is printed:
"./TfMobileNet-Armnn -d imagenet -m model/ -e 1"

Thanks

**Comment by MatthewARM** [comment]
Hi @xiaomin05 there is a defect in the tests included ArmNN 18.08 which stops profiling data from being printed. The issue has been fixed in the development branch and the fix will be part of the next release.

The defect only affects the test programs included with ArmNN and will not affect your application.

If you want to try the fix for yourself the patch is here: https://git.mlplatform.org/ml/armnn.git/commit/?h=refs/heads/master&id=2b7a1581f18b88b55153d4edc5cee0e602fd1bfc

You may also be interested in https://git.mlplatform.org/ml/armnn.git/commit/?h=refs/heads/master&id=e4ba53a85c559d4fe574305276ac815cf7995762 which improves the performance of the profiling mechanism for the CpuAcc backend.

**Comment by xiaomin05** [comment]
Thanks for the help, I could now get the profile data.

One question about the output, does raw value represent measurements for
all calls during one inference
or all inferences ?

**Comment by xiaomin05** [comment]
Can we also get the MACs used in each functional call?

**Comment by MatthewARM** [comment]
Hi @xiaomin05 ArmNN doesn't have any code to retrieve the hardware counters that would be needed for that. I would suggest that you should use a fully featured profiler such as Arm Streamline https://developer.arm.com/products/software-development-tools/ds-5-development-studio/streamline which will be able to do a full system profile and gather hardware counters over your test run.

**Comment by MatthewARM** [comment]
Hi @xiaomin05 I hope I was able to answer your question, let me know if there's anything more I can do to help.
